spring.datasource.url=jdbc:postgresql://localhost:5432/nome_do_banco
spring.datasource.username=seu_usuario_aqui
spring.datasource.password=sua_senha_aqui

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=COLE_SUA_FRONTEND_API_URL_AQUI/.well-known/jwks.json